export const DUMMY_DB = {
  projects: [
    {
      image_url: "/assets/images/Portfolio_home.jpg",
      bg_img: "/assets/images/metal.jpg",
      title: "Admin Dashboard - responsive",
      year: 2022,
      notes: [
        "IBM cloud",
        "Cloud foundary",
        "Cloudant",
        "React",
        "CI/CD Pipeline",
      ],
      icon: "language",
      host: "IBM",
      type: "WEB",
    },
    {
      image_url: "/assets/images/Portfolio_home.jpg",
      bg_img: "/assets/images/metal.jpg",
      title: "ShoeHub - responsive",
      year: 2021,
      notes: [
        "IBM cloud",
        "Cloud foundary",
        "Cloudant",
        "React",
        "CI/CD Pipeline",
      ],
      icon: "language",
      host: "IBM",
      type: "WEB",
    },
    {
      image_url: "/assets/images/Portfolio_home.jpg",
      bg_img: "/assets/images/metal.jpg",
      title: "Shop with me - Mobile App ios/android",
      year: 2021,
      notes: [
        "IBM cloud",
        "Cloud foundary",
        "Cloudant",
        "React",
        "CI/CD Pipeline",
      ],
      icon: "phone_iphone",
      host: "IBM",
      type: "WEB",
    },
    {
      image_url: "/assets/images/Portfolio_home.jpg",
      bg_img: "/assets/images/metal.jpg",
      title: "Automation with Python - Case study",
      year: 2021,
      notes: [
        "IBM cloud",
        "Cloud foundary",
        "Cloudant",
        "React",
        "CI/CD Pipeline",
      ],
      icon: null,
      host: null,
      type: "python",
      Logo: "/assets/images/certificates/python.png",
    },
  ],
  certifications: [
    {
      name: "Full Stack Cloud Developer",
      image_url: "/images/certificates/GMP.png",
      verify: "https://coursera.org/verify/professional-cert/UEGVCEZFG582",
      author: "IBM",
      Logo: "/images/certificates/IBM.png",
      badge: null,
    },

    {
      name: "IT Automation with Python",
      image_url: "/images/certificates/GMP.png",
      verify: "https://coursera.org/verify/professional-cert/UN2U8XRQFEK5",
      author: "Google",
      Logo: "images/certificates/Google.png",
      badge: "/images/certificates/GIPT_BADGE.png",
    },

    {
      name: "Project Management Professional",
      image_url: "/images/certificates/GMP.png",
      verify: "https://coursera.org/verify/professional-cert/2TB5WW2WMVSQ",
      author: "Google",
      Logo: "/images/certificates/Google.png",
      badge: "/images/certificates/GPMP_BADGE.png",
    },

    {
      name: "Msc. Metallic Materials Technology",
      image_url: "/images/Msc.png",
      verify: null,
      author: "TU Bergakademie Freiberg, Germany",
      badge: null,
      Logo: null,
    },
  ],
  skills: [
    "React",
    // IBM CLOUD
    "HTML",
    "CSS",
    "JavaScript",
    "Typescript",
    "Python",
    "GitHub",
    "GitHub actions",
    "Node.js",
    "Cloud Native practices",
    "DevOps",
    "CI/CD",
    "Containers",
    "Docker",
    "Kubernetes",
    "OpenShift",
    "Databases",
    "SQL",
    "NoSQL",
    "Django ORM",
    "Bootstrap",
    "Application Security",
    "Microservices",
    "Serverless computing",
    // Automation with Python subs
    "Computer Networking",
    "IT infrastructural Services",
    "IT Support",
    "Operating Systems",
    "Security",
    "System Administration",
    "Troubleshooting",
    "Debugging",
    "Automation with Python",
    // Project Management
    "Agile Project Management",
    "Budgeting And Procurement",
    "Effective Communication",
    "Process Improvement",
    "Project Management",
    "Project Scoping And Planning",
    "Risk Management",
    "Stakeholder Management",
    "Work Management Tools",
  ],
};
